### ISSUE TITLE
Register gerrit.<mycompany.com> URL

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#112]
Hi,
This is similar to #67. 

Clicking on URL link in Android opens suggestion popup with applications to open the link.

Is it possible to register URL for rview so that it would open gerrit.<mycompany.com> links with rview?

**Comment by jruesga** [comment]
Hi @vlotorev, unfortunately no. Regular expressions in Android manifest are very limited. For `android:host` the wildcard `*` can only be defined at the first of the expression, just for  matching subdomains. The impedes me to configure such url (gerrit.<mycompany.com>) to match generic hosts. And, I can't simple match everything because that will associate any single link with Rview.
