### ISSUE TITLE
Setting up notifications 

### ISSUE THREAD

**Issue by deadman96385** [jruesga/rview#12]
Is there anything other then installing the plugin on the server to enable it? Like a custom config?

Nothing is showing up in the notifications for me

**Comment by jruesga** [comment]
@deadman96385 yes, you need to setup the Firebase server token. This is link has the plugin configuration (https://github.com/jruesga/gerrit-cloud-notifications-plugin/blob/master/src/main/resources/Documentation/config.md). At least, you should add this entry to the gerrit.config file.

```
[plugin "cloud-notifications"]
        serverToken = <SERVER_API_KEY>
```

To get the server key, you should go to the Firebase console (https://console.firebase.google.com/?hl=es), and create a new project. Into the project, in the project settings, there is a "cloud messaging" tab. That tab contains the server key (use the longest on). An reboot the gerrit instance to get the new configuration.

After configure the server, you should enable the notifications for the account you want to configure and choose what events do you want to receive.

**Comment by jruesga** [comment]
@deadman96385 please, let me know if you manage to setup the gerrit instance and receive push notifications.

**Comment by thompatry** [comment]
I work with @deadman96385 on the same team and I set this up on the Exynos5420 Gerrit just like described and it does not work. Can you provide further direction?

**Comment by jruesga** [comment]
@thompatry, set the serverToken plugin property in the $gerrit/etc/gerrit.config as described above should be enough. 

From where to do you download the cloud-notifications plugin? Are you using the stable-2.13 jar? The right one for the 2.13.3 version should be the one located here https://gerrit-ci.gerritforge.com/view/Plugins-2.13/job/plugin-cloud-notifications-stable-2.13.

Does the Rview app displays the  warning "Push notifications requires 'cloud-notifications' plugin to be installed in the Gerrit server instance. Tap here to navigate to the plugin source repository." under the notifications category in the account settings?

Could you run your gerrit ($gerrit/bin/gerrit.sh run) instance from a console instead of from the daemon, and check the console output? Is there a initialization message for the plugin (there should be some traces related to com.ruesga.gerrit or cloud-notifications)? Any stacktrace related to the plugin when an event that should be notified happened?

The plugin is configured to not be logging verbose (only errors should be send to the log in the default configuration). Maybe you can enable increase the plugin log level to see what is happening in the background (https://gerrit-review.googlesource.com/Documentation/cmd-logging-set-level.html)

`$ssh -p <port> <host> gerrit logging set-level com.ruesga.gerrit debug`

I tested the plugin in a local instance I use to test the app, an under that conditions it works, but i using the same project in fcm for the server and the app (but the documentation says that it is possible to send messages from other servers). I will try to check it tonight to see if i can send cross messages.

Sorry for the incovenients :( and thank for testing the plugin.

**Comment by jruesga** [comment]
@deadman96385 @thompatry sorry, my bad. I need to do some changes in the application to allow to receive push notifications from different sender ids (actual only allow the default sender id which is my rview's fcm project). I will prepare a patch to fix it.

**Comment by jruesga** [comment]
@deadman96385 @thompatry I reworked the cloud-notifications plugin to allow to access the senderId and allow a client to obtain a server impersonate token, which allows the app to dialog with different servers. Long story short, you should download the new plugin version from https://gerrit-ci.gerritforge.com/view/Plugins-2.13/job/plugin-cloud-notifications-stable-2.13/ and configure the plugin with at least this two properties:

[plugin "cloud-notifications"]
        serverToken = <SERVER_API_KEY>
        serverSenderId = <SERVER_SENDER_ID>

serverToken is the one you used from firebase and the serverSenderId is the id beside the server token in the firebase console.

After that you should build from source the latest upstream rview code (I'm planned to made a release in a few days with some other changes), and enter disable/enable notifications in the account settings.

That should work. I tested with 2 different firebase accounts and 2 different gerrit server instances and I worked fine.
