### ISSUE TITLE
Wrong user picture

### ISSUE THREAD

**Issue by gmrt** [jruesga/rview#13]
The following assumes that github username == gerrit username, which is not guaranteed: https://github.com/jruesga/rview/blob/d3516bd43bf8449480ed4aa5a41738f122e4ee83/app/src/main/java/com/ruesga/rview/misc/ModelHelper.java#L151-L154

**Comment by jruesga** [comment]
@gmrt yeah, is exactly that (it tries to find a github username from the gerrit username). That doesn't implies anything (there is no correlation between gerrit username and github username). So the sequence (avatar icon preference) is:

1.- If gerrit has avatar available, and is not a gravatar identicon (because those ones are ugly).
2.- Github avatar if Github username matches Gerrit username
3.- Gravatar avatar if Gravatar user email matches Gerrit user email
4.- No icon available (default one)

**Comment by gmrt** [comment]
Well, my gerrit username is X and there's a github user that uses that same username X, so rview is showing his own picture as if it were mine.

**Comment by jruesga** [comment]
Reopened the issue. I need to think on this, but the current code is the better for matching all the situations though.

**Comment by gmrt** [comment]
How about using github's API to check whether the two users belong to the same person? You'd have to add an additional network request, which could be annoying, but I see no way around this problem. Downloading user pictures blindly is not the right approach IMO.

```GET https://api.github.com/users/USERNAME```

**Comment by jruesga** [comment]
Using the github api is not a solution because still have no way to map a Gerrit user to a Github user, because the email can be not public available, so it's just like ask for the same username. In addition, getAvatarUrls is called in most of the case from the ui thread which doesn't allow do network calls.

Yeah, I agree with you that blindly call to github is not the best option, but since 2.11 doesn't support avatars, I need to get one from one of the public avatars apis, and it matches in a big percent of the cases. 

For 2.13, Gerrit returns its own avatars, but as I said before when it returns identicons from gravatar those are really ugly (it works nicely for others repos like the google ones that use its own imagery).

I don't see how to fix this for your case, except if i remove github an gravatar urls, but this will give a bad ux in versions prior to 2.13. I prefer a better ux, that empty avatars.

**Comment by gmrt** [comment]
> Using the github api is not a solution because still have no way to map a Gerrit user to a Github user, because the email can be not public available, so it's just like ask for the same username.

Yes, what I meant is using the Github image only if the emails match. Obviously this would result in a lower number of matches, but you wouldn't get random images.

> In addition, getAvatarUrls is called in most of the case from the ui thread which doesn't allow do network calls

That's exactly what I was worried of, I understand such a change would require modifications that aren't worth it.

> For 2.13, Gerrit returns its own avatars, but as I said before when it returns identicons from gravatar those are really ugly (it works nicely for others repos like the google ones that use its own imagery).

FYI Github allows you to get identicons: `https://github.com/identicons/USERNAME.png`


Anyway, I was just annoyed by the fact that some random face was associated to my account, but I guess a can simply add some dummy image to hide that.

**Comment by jruesga** [comment]
Switched the fetch order in 7a4427e300e6084b0b61e38b3bba9386d9e02b38 (first gravatar and later github). This gives you an opportunity to setup your desired avatar in gravatar based in an email (which is commonly more trusted).
