### ISSUE TITLE
Open link in app 

### ISSUE THREAD

**Issue by lokal-profil** [jruesga/rview#14]
It would be great if the app would suggest to open gerrit links in the app.

I believe [intent filters](http://www.vogella.com/tutorials/AndroidIntent/article.html#what-is-an-intent-filter) is what is needed.

Ideally would be that this is triggered by the gerrit links of any profiles but simply doing it for each of the predefined repos would also be a solution.

**Comment by jruesga** [comment]
@lokal-profil it's impossible to do for every repository created, because I can't create new intent-filters on the fly and regex in intent filters are very limited (specially when url have # character; the rest of the string since # is ignored for matching in the intent-filter path).

Said that, look at the "links" branch ;) The gradle build script create disabled activity alias for every entry in the repositories.json file, and later, those activities are enabled/disabled according to the user accounts (that means only repositories with an active account are handled by the app).
I'm still testing it, but seems to work fine so far.

**Comment by jruesga** [comment]
The 'Gerrit urls handling' is now merged into master.
