### ISSUE TITLE
"5 decades ago"

### ISSUE THREAD

**Issue by dulek** [jruesga/rview#16]
There's some timezone related issue in incoming patch list view, one patch is even shown as "5 decades ago". I guess this is more or less Jan 2017-Jan 1970? Screenshot attached. My timezone in Gerrit matches TZ on my phone.

![screenshot](https://cloud.githubusercontent.com/assets/208288/21848607/f4981cc6-d801-11e6-9f4a-7ef1109857ee.jpg)

**Comment by jruesga** [comment]
Yep, I'm aware of this bug, but since is absolutely puntual (I didn't see it in a long time), I couldn't trace it and determine if it is a data glitch on gerrit (I tend to thought) or a bug in the code.

If you are running a debug build, and can reproduce it, could you extract a logcat (it should contain the requests and response to server). That will help to determine the origin of the problem. Thx.

**Comment by jruesga** [comment]
https://github.com/jruesga/rview/commit/b2f67ade7bc68b47db7bdcb9ed6fb9407e052f70
