### ISSUE TITLE
Issues with creating new changes

### ISSUE THREAD

**Issue by teemumurtola** [jruesga/rview#38]
At least on Android 7.1.2 (and Gerrit 2.14.1, if it matters), there are several problems with the UI dialog used to create new changes from scratch.

First is that the project completion drop-down only shows the first five projects from the Gerrit instance; typing some initial characters only filters this list, but does not search for additional projects. If the Gerrit instance has more than a few projects, it is not possible to create changes for others than the first few.

Second is that manually typing in the project and branch names doesn't enable the Create button. The button only gets enabled if the project and branch are selected from the dropdown. It should work the same way if the same selections are typed into the box.

**Comment by jruesga** [comment]
1) I cannot show all the list of projects in the combo because that needs to be scrolled and clashes with the keyboard that will close the dropdown. Said you, there is space to improvement by fetching the projects by regexp instead of full qualified name. I will fix that.

2) Yes, that's the correct behaviour, just to be sure the user typed an existent project and branch (otherwise there is too much possibilities that the user typed a wrong project and the request will just simple fails because the project typed doesn't exists). This window requires project and branch to be selected from the combo and subject not be empty (topic is optional). When all requisites are met then the create button is enabled.

**Comment by jruesga** [comment]
0291b18be72feac1799a78c25767732aa727b0b8 should fix issue 1. Issue 2 should be reasonable if issue is fixed. Feel free to reopen the issue if you still found the dialog unusable.
