### ISSUE TITLE
Can't connect to private gerrit instance

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#42]
Registering the private Gerrit instance in Rview ends with 'Endpoint is not Gerrit instance error'.

Server uses self signed certificate.
The same URL opens in browser without issues. I have to accept certicate though.

**Comment by jruesga** [comment]
Thanks for the bug report. Fixed in https://github.com/jruesga/rview/commit/765b9f9bac3f53e52a05f7dae3e92538301236fe

You still need to check "Trust all server certificates" on the repository's wizard page. Be aware that this option could expose the connection between your device and your gerrit service instance to MITM attacks, since the app must trust in any certificate presented by the server.

**Comment by vlotorev** [comment]
Great. Thanks for fixing it - that was fast. When will this commit be available as release on Google Play?

**Comment by jruesga** [comment]
I will do a release tonight.
