### ISSUE TITLE
Can't login to private gerrit instance

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#43]
Using version 1.5.5 (After fixing #42) I can add private Gerrit instance with self-signed certificate but can't login.
After enabling authenticated access and filling in Username and Password fields "Invalid username or password" error occurs.

Working as Anonymous coward allows browsing the issues but not commenting them.

I use Gerrit v2.14.2.

**Comment by jruesga** [comment]
You MUST login with your own HTTP password, not with your normal login user/password. If in the account wizard page you tap on the overflow button and show the help dialog, it will raise a help dialog explaining the authentication process. Basically there are two kind of authentication modes:

1.- Plain password
2.- .gitcookies (mostly all Google Gerrit instances)

In both cases you must go to your Gerrit settings in a web browser and then goto to HTTP Password (or click in the hyperlink "here" in the account wizard page). In this page depending on the authentication mode you will have:


1.- Plain password

Username => username
Password => password

You have to save the password outside Gerrit if you want to use multiple devices, because once genereated (in 2.14+ versions), it is not possible to obtain it again. The most easy/convenient method, it is to use the click 'here' link and click in the regenerate and copy button and then paste the password in the password box.


2.- .gitcookies

In the HTTP password page you can generate a new git cookie associated to your Google account. The Gerrit service will present some instructions to include this new generated cookie in a file called .gitcookies to login though the git tool. You can localize the information to introduce in the account authentication fields in the instruction presented, by localizing the expression **git-<username>.gmail.com**=**<password>**. Just copy and paste these _git-<username&gt;.gmail.com>_ and _<password>_ values into the account authentication fields.


Sorry but Gerrit doesn't support other authentication methods (like OAuth) for the its REST api.

Let me know if these steps help you with your authentication issue.

**Comment by vlotorev** [comment]
Thanks for an explanation. Using HTTP password did the trick. I logined successfully.
