### ISSUE TITLE
Can't switch keyboard layout on edit

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#58]
I have UTF8 text file with non ascii characters in repository.

In case I try editing this file in app then all characters are displayed ok but I can't switch keabord layout from English to needed one.
I use google keyboard, it has globus button to change layout, clicking on it doesn't change layot in the app.

**Comment by jruesga** [comment]
Because a bug in ace editor i had to disable non latin keyboards (https://github.com/jruesga/rview/blob/master/app/src/main/java/com/ruesga/rview/widget/AceWebView.java#L62). The problem was caused by an IME change in chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=118639 https://github.com/ajaxorg/ace/issues/2964 https://github.com/ajaxorg/ace/issues/1917

Without this commit editing was doing weird things, like deleting 2 chars on deletion and other bad editing things.

I upgraded the ace editor to 1.2.9 in the last version. I will recheck if they fixed the issue or if it is still present.

**Comment by jruesga** [comment]
Ace 1.2.9 fixes some of the IME bugs, but some still remains. Anyway, 56855c1ded27e7d942e26f2b2ccce97137411b4d seems a good parity between do not support non-IME keyboards (and have no editing bugs) and support IME keyboards (with some minors bugs), and GBoard, AOSP and Samsung seems to behave relativelly well.
