### ISSUE TITLE
Support for HTTP basic authentication

### ISSUE THREAD

**Issue by hoxi** [jruesga/rview#59]
Our Gerrit instance is served behind HTTP basic authentication, it would be great if this could be supported as well. 

I tried also connecting using:
https://user:password@server.com without luck.

**Comment by jruesga** [comment]
The rest api always authenticated though a generated http password, which you can generate in the "http password" settings section once your logged in the gerrit site. You can input the username and password you obtained from that setting page to login with Rview.

That works except in the case all gerrit site was protected from an external http server using a reverse proxy. In that case the basic auth done by the http server is not enough for the rest api that still expect the "http password".

I will try to open a ticket to see if there is s way to bypass this configuration.

**Comment by jruesga** [comment]
I opened ticket at https://groups.google.com/forum/#!topic/repo-discuss/FCdnSIsPwfc

**Comment by hoxi** [comment]
Thanks for your effort looking into this! Seems like Gerrit could use an option to support different HTTP & basic auth passwords, let's see what they respond to your report... 

In our case the Gerrit HTTP & reverse proxy http basic auth password is synchronized, so maybe your client could use the entered http user&password also for basic authentication (if basic auth is detected) ? The Gerrit connector for Android studio seem to work that way. If Gerrit will provide support for differentiated credentials, then your client could be updated for this as well.

Thanks for a great app!

**Comment by jruesga** [comment]
@hoxi Rview support both authenticated method: digest and basic https://github.com/jruesga/rview/blob/master/gerrit/src/main/java/com/ruesga/rview/gerrit/GerritApiClient.java#L86

Are you sure that generated "http password" from your profile settings doesn't work for you?

With the HTTP authentication method, all the authentication is done by the http server and Gerrit only checks the passed Authentication header to obtain the username. The only problem i saw was when the http server protects all the gerrit resources instead of only /login/ as they recommends. With this last one configuration to access to the rest api you still need the generated "http password". I opened the case for the former (in which the basic auth psssword of your http server should be enough, but there is a http filter that still checks for the password obtained from the authorization header and doesn't match with what the rest api expects that is a generated "http password"). For the rest of the cases the generated "http password" is one to use.

**Comment by jruesga** [comment]
@hoxi if your site is protected for the http server, there is an option in gerrit "auth.trustContainerAuth" that bypass any auth check in Gerrit and relay exclusively in the http server auth. That property doesn't requires you to use a generated "http password".

**Comment by jruesga** [comment]
Added support for XSRF_TOKEN authentication in fe58f8e024f4c5f7851828d17fbdb2445a25d226

@hoxi with this change you are supposed to logged with your user/password using http basic auth.
