### ISSUE TITLE
Comment quoting doesn't work

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#88]
There is Reply icon in the top right corner for each comment on the change screen.
Tapping the icon results in following text
being inserted into comment field (text is literal):
```
 [QUOTE](1 comment)
[/QUOTE]
```
So quoting is not actually performed.

**Comment by vlotorev** [comment]
Nothing is inserted beetwen [QUOTE][/QUOTE]. My expectation that quote button would insert not only tag but also quoted comment text.

**Comment by jruesga** [comment]
Should be fixed with the following commits:

7322e5147a34b098014e9017694e54142b1497c1
989e20b1e7ab2ba5446a9b460963223c3711f93d
027f3cbf55be3ae43c577bb3bb9c31e68b9ce3df
7e293512d3f7bee288396efcc26a2d47a6a52ae1
5147adf326320d819dda6548490556e2a1f42747
cf57305ff420edbb2cd854012ef6d441115726a3

I add a new quote action in inline comments. Quoting of messages just quote the message not the associated inline comments.

**Comment by vlotorev** [comment]
Thank you, now quoting works as expected.

чт, 19 июля 2018 г., 22:23 Jorge Ruesga <notifications@github.com>:
